use std::fmt::{Display, Formatter, Result as FmtResult};

/// Disk ids cannot be generated by atomics.
/// They must be stored somewhere in the database
pub type PageId = u64;
pub type BlockId = u64;
pub type Lsn = u64;
pub type RowId = u64;
pub type ObjectId = u64;
pub type TransactionId = u64;

pub const PAGE_ZERO: PageId = 0;
pub const META_TABLE_ROOT: PageId = PAGE_ZERO;
pub const META_INDEX_ROOT: PageId = 1;

/// Logical identifier for a tuple (table + row)
#[derive(Debug, PartialEq, Eq, Ord, PartialOrd, Hash, Clone, Copy)]
pub struct LogicalId(ObjectId, RowId);

impl Display for LogicalId {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "Table {}, row {}", self.0, self.1)
    }
}

impl LogicalId {
    pub fn new(table: ObjectId, row: RowId) -> Self {
        Self(table, row)
    }

    pub fn table(&self) -> ObjectId {
        self.0
    }

    pub fn row(&self) -> RowId {
        self.1
    }
}
