//! Types module.
use std::{
    cmp::Ordering,
    error::Error,
    fmt::{Display, Formatter, Result as FmtResult},
    hash::{Hash, Hasher},
    io::Error as IoError,
    str::Utf8Error,
};

use crate::arithmetic_op;
use crate::types::core::TypeCast;
use rkyv::rancor::Error as RkyvError;
pub(crate) mod core;
pub(crate) mod macros;

use axmos_derive::AutogeneratedDataType;

pub mod blob;
pub mod bool;
pub mod id;
pub mod numeric;
pub mod varint;

pub use blob::{Blob, BlobRef};
use bool::Bool;
use bytemuck::PodCastError;
pub use id::*;
pub use numeric::{Float32, Float64, Int32, Int64, UInt32, UInt64};
pub use varint::VarInt;

#[derive(Debug)]
pub enum SerializationError {
    InvalidVarIntPrefix,
    UnexpectedEof,
    BytemuckError(PodCastError),
    NotSupported,
    Io(IoError),
    Rkyv(RkyvError),

    Other(String),
}

impl Display for SerializationError {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        match self {
            Self::InvalidVarIntPrefix => f.write_str("Incomplete or invalid VarInt prefix"),
            Self::UnexpectedEof => f.write_str("Unexpected EOF"),
            Self::BytemuckError(err) => write!(f, "Pod cast error: {err}"),
            Self::Io(err) => write!(f, "IO error {err}"),
            Self::NotSupported => f.write_str("Unsupported deserialization type"),
            Self::Rkyv(e) => write!(f, "Rkyv Error {e}"),
            Self::Other(string) => f.write_str(string),
        }
    }
}

impl From<PodCastError> for SerializationError {
    fn from(value: PodCastError) -> Self {
        Self::BytemuckError(value)
    }
}

impl From<RkyvError> for SerializationError {
    fn from(value: RkyvError) -> Self {
        Self::Rkyv(value)
    }
}

impl From<IoError> for SerializationError {
    fn from(value: IoError) -> Self {
        Self::Io(value)
    }
}

#[derive(Debug)]
pub enum TypeSystemError {
    Utf8Error(Utf8Error),
    UnexpectedDataType(DataTypeKind),
    SerializationError(SerializationError),
}

impl Error for TypeSystemError {}

impl Display for TypeSystemError {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        match self {
            Self::Utf8Error(e) => write!(f, "utf8 error: {e}"),
            Self::SerializationError(e) => write!(f, "deserialization error: {e}"),
            Self::UnexpectedDataType(dt) => write!(f, "unexpected data type: {dt}"),
        }
    }
}
impl From<Utf8Error> for TypeSystemError {
    fn from(value: Utf8Error) -> Self {
        Self::Utf8Error(value)
    }
}

impl From<SerializationError> for TypeSystemError {
    fn from(value: SerializationError) -> Self {
        Self::SerializationError(value)
    }
}
pub type TypeSystemResult<T> = Result<T, TypeSystemError>;
pub type SerializationResult<T> = Result<T, SerializationError>;

#[derive(Debug, Clone, AutogeneratedDataType)]
#[delegate(
    trait = "crate::types::core::Hashable",
    method = "hash128",
    return_type = "u128",
    default = "0"
)]
#[delegate(
    trait = "crate::types::core::Hashable",
    method = "hash128",
    target = "ref",
    return_type = "u128",
    default = "0"
)]
#[delegate(
    trait = "crate::types::core::Hashable",
    method = "hash64",
    return_type = "u64",
    default = "0"
)]
#[delegate(
    trait = "crate::types::core::RuntimeSized",
    method = "runtime_size",
    return_type = "usize",
    default = "0"
)]
#[delegate(
    trait = "crate::types::core::RuntimeSized",
    method = "runtime_size",
    return_type = "usize",
    target = "ref",
    default = "0"
)]
#[delegate(
    trait = "crate::types::core::TypeClass",
    const = "SIZE",
    target = "kind",
    as = "fixed_size",
    return_type = "Option<usize>",
    default = "None"
)]
#[delegate(
    trait = "crate::types::core::TypeClass",
    const = "ALIGN",
    target = "kind",
    as = "align",
    return_type = "usize",
    default = "1"
)]
#[delegate(
    trait = "crate::types::core::TypeClass",
    const = "ALIGN",
    target = "main",
    as = "align",
    return_type = "usize",
    default = "1"
)]
#[delegate(
    trait = "crate::types::core::SerializableType",
    method = "write_to",
    args = "&self, writer: &mut [u8], cursor: usize",
    target = "main",
    call_args = "inner, writer, cursor",
    return_type = "SerializationResult<usize>",
    default = "Err(SerializationError::NotSupported)"
)]
#[delegate(
    trait = "crate::types::core::SerializableType",
    method = "serialize",
    args = "&self",
    target = "main",
    call_args = "inner",
    return_type = "SerializationResult<Box<[u8]>>",
    default = "Err(SerializationError::NotSupported)"
)]
#[delegate(
    trait = "crate::types::core::DeserializableType",
    method = "reinterpret_cast",
    target = "kind",
    args = "self, buffer: &[u8]",
    call_args = "buffer",
    return_type = "SerializationResult<(DataTypeRef<'_>, usize)>",
    default = "Err(SerializationError::NotSupported)",
    wrap_variant = "ref,result,tuple"
)]
#[delegate(
    trait = "crate::types::core::DeserializableType",
    method = "deserialize",
    target = "kind",
    args = "self, buffer: &[u8], cursor: usize",
    call_args = "buffer, cursor",
    return_type = "SerializationResult<(DataTypeRef<'_>, usize)>",
    default = "Err(SerializationError::NotSupported)",
    wrap_variant = "ref,result,tuple"
)]
#[delegate(
    trait = "crate::types::core::NumericOps",
    method = "abs",
    target = "main",
    args = "&self",
    return_type = "DataType",
    default = "DataType::Null",
    wrap_variant = "main",
    filter_attributes = "numeric"
)]
#[delegate(
    trait = "crate::types::core::NumericOps",
    method = "floor",
    target = "main",
    args = "&self",
    return_type = "DataType",
    default = "DataType::Null",
    wrap_variant = "main",
    filter_attributes = "numeric"
)]
#[delegate(
    trait = "crate::types::core::NumericOps",
    method = "ceil",
    target = "main",
    args = "&self",
    return_type = "DataType",
    default = "DataType::Null",
    wrap_variant = "main",
    filter_attributes = "numeric"
)]
#[delegate(
    trait = "crate::types::core::NumericOps",
    method = "round",
    target = "main",
    args = "&self",
    return_type = "DataType",
    default = "DataType::Null",
    wrap_variant = "main",
    filter_attributes = "numeric"
)]
#[delegate(
    trait = "crate::types::core::NumericOps",
    method = "sqrt",
    target = "main",
    args = "&self",
    return_type = "DataType",
    default = "DataType::Null",
    wrap_variant = "main",
    filter_attributes = "numeric"
)]
#[config(
    reference_trait = "crate::types::core::TypeRef<'a>",
    owned_trait = "crate::types::core::TypeOwned"
)]
pub enum DataType {
    #[null]
    Null,
    Bool(Bool),

    #[numeric]
    Int(Int32),

    #[numeric]
    BigInt(Int64),

    #[numeric]
    UInt(UInt32),

    #[numeric]
    BigUInt(UInt64),

    #[numeric]
    Float(Float32),

    #[numeric]
    Double(Float64),

    Blob(Blob),
}
crate::impl_datatype_ord_traits!(DataType);
crate::impl_datatype_ord_traits!(DataTypeRef<'_>);

impl Eq for DataType {}
impl Eq for DataTypeRef<'_> {}

crate::impl_datatype_hash!(DataType);
crate::impl_datatype_hash!(DataTypeRef<'_>);

impl DataType {
    arithmetic_op!(add, promoted_add);
    arithmetic_op!(sub, promoted_sub);
    arithmetic_op!(mul, promoted_mul);
    arithmetic_op!(div, promoted_div);
    arithmetic_op!(rem, promoted_rem);

    /// Try to cast this DataType to a different DataTypeKind
    pub fn try_cast(&self, target: DataTypeKind) -> TypeSystemResult<DataType> {
        // Same kind, just clone
        if self.kind() == target {
            return Ok(self.clone());
        }

        match (self, target) {
            // Null stays null
            (DataType::Null, _) => Ok(DataType::Null),

            // From Int
            (DataType::Int(v), DataTypeKind::BigInt) => Ok(DataType::BigInt(
                TypeCast::<Int64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Int(v), DataTypeKind::UInt) => Ok(DataType::UInt(
                TypeCast::<UInt32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Int(v), DataTypeKind::BigUInt) => Ok(DataType::BigUInt(
                TypeCast::<UInt64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Int(v), DataTypeKind::Float) => Ok(DataType::Float(
                TypeCast::<Float32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Int(v), DataTypeKind::Double) => Ok(DataType::Double(
                TypeCast::<Float64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),

            // From BigInt
            (DataType::BigInt(v), DataTypeKind::Int) => Ok(DataType::Int(
                TypeCast::<Int32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::BigInt(v), DataTypeKind::UInt) => Ok(DataType::UInt(
                TypeCast::<UInt32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::BigInt(v), DataTypeKind::BigUInt) => Ok(DataType::BigUInt(
                TypeCast::<UInt64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::BigInt(v), DataTypeKind::Float) => Ok(DataType::Float(
                TypeCast::<Float32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::BigInt(v), DataTypeKind::Double) => Ok(DataType::Double(
                TypeCast::<Float64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),

            // From UInt
            (DataType::UInt(v), DataTypeKind::Int) => Ok(DataType::Int(
                TypeCast::<Int32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::UInt(v), DataTypeKind::BigInt) => Ok(DataType::BigInt(
                TypeCast::<Int64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::UInt(v), DataTypeKind::BigUInt) => Ok(DataType::BigUInt(
                TypeCast::<UInt64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::UInt(v), DataTypeKind::Float) => Ok(DataType::Float(
                TypeCast::<Float32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::UInt(v), DataTypeKind::Double) => Ok(DataType::Double(
                TypeCast::<Float64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),

            // From BigUInt
            (DataType::BigUInt(v), DataTypeKind::Int) => Ok(DataType::Int(
                TypeCast::<Int32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::BigUInt(v), DataTypeKind::BigInt) => Ok(DataType::BigInt(
                TypeCast::<Int64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::BigUInt(v), DataTypeKind::UInt) => Ok(DataType::UInt(
                TypeCast::<UInt32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::BigUInt(v), DataTypeKind::Float) => Ok(DataType::Float(
                TypeCast::<Float32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::BigUInt(v), DataTypeKind::Double) => Ok(DataType::Double(
                TypeCast::<Float64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),

            // From Float
            (DataType::Float(v), DataTypeKind::Int) => Ok(DataType::Int(
                TypeCast::<Int32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Float(v), DataTypeKind::BigInt) => Ok(DataType::BigInt(
                TypeCast::<Int64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Float(v), DataTypeKind::UInt) => Ok(DataType::UInt(
                TypeCast::<UInt32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Float(v), DataTypeKind::BigUInt) => Ok(DataType::BigUInt(
                TypeCast::<UInt64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Float(v), DataTypeKind::Double) => Ok(DataType::Double(
                TypeCast::<Float64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),

            // From Double
            (DataType::Double(v), DataTypeKind::Int) => Ok(DataType::Int(
                TypeCast::<Int32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Double(v), DataTypeKind::BigInt) => Ok(DataType::BigInt(
                TypeCast::<Int64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Double(v), DataTypeKind::UInt) => Ok(DataType::UInt(
                TypeCast::<UInt32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Double(v), DataTypeKind::BigUInt) => Ok(DataType::BigUInt(
                TypeCast::<UInt64>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),
            (DataType::Double(v), DataTypeKind::Float) => Ok(DataType::Float(
                TypeCast::<Float32>::try_cast(v)
                    .ok_or(TypeSystemError::UnexpectedDataType(self.kind()))?,
            )),

            // Bool to numeric
            (DataType::Bool(v), DataTypeKind::Int) => {
                Ok(DataType::Int(Int32(if v.0 { 1 } else { 0 })))
            }
            (DataType::Bool(v), DataTypeKind::BigInt) => {
                Ok(DataType::BigInt(Int64(if v.0 { 1 } else { 0 })))
            }
            (DataType::Bool(v), DataTypeKind::UInt) => {
                Ok(DataType::UInt(UInt32(if v.0 { 1 } else { 0 })))
            }
            (DataType::Bool(v), DataTypeKind::BigUInt) => {
                Ok(DataType::BigUInt(UInt64(if v.0 { 1 } else { 0 })))
            }
            (DataType::Bool(v), DataTypeKind::Float) => {
                Ok(DataType::Float(Float32(if v.0 { 1.0 } else { 0.0 })))
            }
            (DataType::Bool(v), DataTypeKind::Double) => {
                Ok(DataType::Double(Float64(if v.0 { 1.0 } else { 0.0 })))
            }

            // Numeric to Bool (non-zero = true)
            (DataType::Int(v), DataTypeKind::Bool) => Ok(DataType::Bool(Bool(v.0 != 0))),
            (DataType::BigInt(v), DataTypeKind::Bool) => Ok(DataType::Bool(Bool(v.0 != 0))),
            (DataType::UInt(v), DataTypeKind::Bool) => Ok(DataType::Bool(Bool(v.0 != 0))),
            (DataType::BigUInt(v), DataTypeKind::Bool) => Ok(DataType::Bool(Bool(v.0 != 0))),
            (DataType::Float(v), DataTypeKind::Bool) => Ok(DataType::Bool(Bool(v.0 != 0.0))),
            (DataType::Double(v), DataTypeKind::Bool) => Ok(DataType::Bool(Bool(v.0 != 0.0))),

            // Unsupported casts
            _ => Err(TypeSystemError::UnexpectedDataType(self.kind())),
        }
    }
}
