use proc_macro::TokenStream;
use proc_macro_error::proc_macro_error;

mod datatype;

#[proc_macro_error]
#[proc_macro_derive(AutogeneratedDataType, attributes(null, numeric, delegate, config))]
pub fn data_type_derive(input: TokenStream) -> TokenStream {
    let input = proc_macro2::TokenStream::from(input);
    datatype::autogen_data_type_impl(input).into()
}
