use proc_macro::TokenStream;
use proc_macro_error::proc_macro_error;

mod core;

#[proc_macro_error]
#[proc_macro_derive(AutogeneratedDataType, attributes(null, delegate, ref_trait))]
pub fn data_type_derive(input: TokenStream) -> TokenStream {
    let input = proc_macro2::TokenStream::from(input);
    core::autogen_data_type_impl(input).into()
}
